FORMAT: 1A
HOST: http://giv-gwot-vst.uni-muenster.de:3333/api

# Geospatial Web of Things - Virtual Smart Things API

**HOST** (master): `http://giv-gwot-vst.uni-muenster.de:3333/api`


# Data Structures

## Sensor (object)
+ sensor_id: `1` (number, optional) - `null` (Default)
+ device_id: `rpi-1` (string, required) - The DeviceId of a Sensor
+ description: `RPi am Wersehaus`(string, optional) - The description of the sensor
+ lng: `7.59572` (number, required) - The Longitude-value of the location
+ lat: `51.969415` (number, required) - The Latitude-value of the location


## Public Sensors [/sensors]

### List all public Sensors [GET]

+ Response 200 (application/json)

        [
            {
                "sensor_id" : "1" ,
                "created" : "",
                "updated": "",
                "sensor_description": "RPi Water gauge sensor",
                "lng": 7.59572,
                "lat": 51.969415
            }, {
                "sensor_id" : "2" ,
                "created" : "",
                "updated": "",
                "sensor_description": "Arduino Water gauge sensor",
                "lng": 7.59575,
                "lat": 51.969425
            }
        ]


## Private Sensors [/users/{username}/sensors]

+ Parameters

    + username: `nicho90` (string, required) - The Username of a User


### List all private Sensors of a User [GET]

+ Request

    + Headers

            token : token

+ Response 200 (application/json)

        [
            {
                "sensor_id" : "1" ,
                "created" : "",
                "updated": "",
                "sensor_description": "RPi Water gauge sensor",
                "lng": 7.59572,
                "lat": 51.969415
            }, {
                "sensor_id" : "2" ,
                "created" : "",
                "updated": "",
                "sensor_description": "Arduino Water gauge sensor",
                "lng": 7.59575,
                "lat": 51.969425
            }
        ]


### Create a Sensor [POST]

+ Request

    + Headers

            token : token
            Content-Type : application/json

+ Attributes (Sensor)

+ Response 201 (application/json)

        {
            "sensor_id" : "1" ,
            "created" : "",
            "updated": "",
            "sensor_description": "RPi Water gauge sensor",
            "lng": 7.59572,
            "lat": 51.969415
        }


## Private & public Sensors [/users/{username}/sensors?public={public}]

### List all private Sensors of a User and all public Sensors [GET]

+ Request
    
    + Headers

            token : token

+ Parameters
    
    + public: `true` (boolean, required) - Merge all private Sensors with all public Sensors

+ Response 200 (application/json)

        [
            {
                "sensor_id" : "1" ,
                "created" : "",
                "updated": "",
                "sensor_description": "RPi Water gauge sensor",
                "lng": 7.59572,
                "lat": 51.969415
            }, {
                "sensor_id" : "2" ,
                "created" : "",
                "updated": "",
                "sensor_description": "Arduino Water gauge sensor",
                "lng": 7.59575,
                "lat": 51.969425
            }
        ]



        
## Public Sensor [/sensors/{sensorId}]

+ Parameters

    + sensorId: `1` (number, required) - The id of a Sensor

### Retrieve a Sensor [GET]

+ Response 200 (application/json)

        {
            "sensor_id" : "1" ,
            "created" : "",
            "updated": "",
            "sensor_description": "RPi Water gauge sensor",
            "lng": 7.59572,
            "lat": 51.969415
        }
        
### Edit a Sensor [PUT]

+ Request
    
    + Headers
        
            Content-Type : application/json

            
+ Response 200 (application/json)

        {
            "sensor_id" : "1" ,
            "created" : "",
            "updated": "",
            "sensor_description": "RPi Water gauge sensor",
            "lng": 7.59572,
            "lat": 51.969415
        }

### Delete a Sensor [DELETE]

+ Response 204



## Forecast [/forecast?lat={lat}&lng={lng}&lang={lang}]

+ Parameters
    
    + lat: `0.0` (number, required) - Latitude value of a Sensor
    + lng: `0.0` (number, required) - Longitude value of a Sensor
    + lang: `en` (string, required) - Language for summaries: `en` (default), `de`
 

### GET a Forecast [GET]

+ Relation: forecast
   
+ Response 200 (application/json)
    
        {
            "latitude": 51.973314,
            "longitude": 7.70013,
            "timezone": "Europe/Berlin",
            "offset": 2,
            "currently": {
                "time": 1464785436,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.2794,
                "precipProbability": 0.49,
                "precipType": "rain",
                "temperature": 22.58,
                "apparentTemperature": 22.58,
                "dewPoint": 20.06,
                "humidity": 0.86,
                "windSpeed": 18.51,
                "windBearing": 14,
                "cloudCover": 0.5,
                "pressure": 1011.84,
                "ozone": 319.16
            },
            "hourly": {
                "summary": "Light rain throughout the day.",
                "icon": "rain",
                "data": [
                    {
                        "time": 1464782400,
                        "summary": "Light Rain",
                        "icon": "rain",
                        "precipIntensity": 0.2337,
                        "precipProbability": 0.47,
                        "precipType": "rain",
                        "temperature": 21.49,
                        "apparentTemperature": 21.49,
                        "dewPoint": 19.35,
                        "humidity": 0.88,
                        "windSpeed": 16.59,
                        "windBearing": 6,
                        "cloudCover": 0.38,
                        "pressure": 1012.17,
                        "ozone": 318.3
                    },
                    {
                        "time": 1464786000,
                        "summary": "Light Rain",
                        "icon": "rain",
                        "precipIntensity": 0.287,
                        "precipProbability": 0.49,
                        "precipType": "rain",
                        "temperature": 22.79,
                        "apparentTemperature": 22.79,
                        "dewPoint": 20.19,
                        "humidity": 0.85,
                        "windSpeed": 18.89,
                        "windBearing": 16,
                        "cloudCover": 0.52,
                        "pressure": 1011.78,
                        "ozone": 319.31
                    },
                    {
                        "time": 1464789600,
                        "summary": "Light Rain",
                        "icon": "rain",
                        "precipIntensity": 0.3505,
                        "precipProbability": 0.51,
                        "precipType": "rain",
                        "temperature": 24.02,
                        "apparentTemperature": 24.02,
                        "dewPoint": 20.92,
                        "humidity": 0.83,
                        "windSpeed": 21.9,
                        "windBearing": 23,
                        "cloudCover": 0.47,
                        "pressure": 1011.31,
                        "ozone": 320.38
                    },
                    {
                        "time": 1464793200,
                        "summary": "Light Rain",
                        "icon": "rain",
                        "precipIntensity": 0.4851,
                        "precipProbability": 0.55,
                        "precipType": "rain",
                        "temperature": 24.32,
                        "apparentTemperature": 24.32,
                        "dewPoint": 21,
                        "humidity": 0.82,
                        "windSpeed": 23.66,
                        "windBearing": 28,
                        "cloudCover": 0.43,
                        "pressure": 1010.87,
                        "ozone": 321.24
                    },
                    {
                        "time": 1464796800,
                        "summary": "Light Rain",
                        "icon": "rain",
                        "precipIntensity": 0.7595,
                        "precipProbability": 0.6,
                        "precipType": "rain",
                        "temperature": 24.01,
                        "apparentTemperature": 24.01,
                        "dewPoint": 20.91,
                        "humidity": 0.83,
                        "windSpeed": 24.49,
                        "windBearing": 31,
                        "cloudCover": 0.51,
                        "pressure": 1010.5,
                        "ozone": 321.95
                    },
                    {
                    "time": 1464800400,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 1.0643,
                    "precipProbability": 0.63,
                    "precipType": "rain",
                    "temperature": 23.21,
                    "apparentTemperature": 23.21,
                    "dewPoint": 20.57,
                    "humidity": 0.85,
                    "windSpeed": 22.42,
                    "windBearing": 36,
                    "cloudCover": 0.74,
                    "pressure": 1010.17,
                    "ozone": 322.45
                  },
                  {
                    "time": 1464804000,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 1.2116,
                    "precipProbability": 0.64,
                    "precipType": "rain",
                    "temperature": 22.06,
                    "apparentTemperature": 22.06,
                    "dewPoint": 19.88,
                    "humidity": 0.87,
                    "windSpeed": 20.13,
                    "windBearing": 40,
                    "cloudCover": 0.98,
                    "pressure": 1009.95,
                    "ozone": 322.27
                  },
                  {
                    "time": 1464807600,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 1.0973,
                    "precipProbability": 0.63,
                    "precipType": "rain",
                    "temperature": 21.04,
                    "apparentTemperature": 21.04,
                    "dewPoint": 19.26,
                    "humidity": 0.9,
                    "windSpeed": 20.42,
                    "windBearing": 37,
                    "cloudCover": 1,
                    "pressure": 1009.88,
                    "ozone": 320.84
                  },
                  {
                    "time": 1464811200,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.856,
                    "precipProbability": 0.61,
                    "precipType": "rain",
                    "temperature": 20.04,
                    "apparentTemperature": 20.04,
                    "dewPoint": 18.67,
                    "humidity": 0.92,
                    "windSpeed": 21.87,
                    "windBearing": 32,
                    "cloudCover": 0.96,
                    "pressure": 1009.93,
                    "ozone": 318.73
                  },
                  {
                    "time": 1464814800,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.6477,
                    "precipProbability": 0.58,
                    "precipType": "rain",
                    "temperature": 19.14,
                    "apparentTemperature": 19.14,
                    "dewPoint": 18.12,
                    "humidity": 0.94,
                    "windSpeed": 22.39,
                    "windBearing": 29,
                    "cloudCover": 0.93,
                    "pressure": 1009.96,
                    "ozone": 317.23
                  },
                  {
                    "time": 1464818400,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.5258,
                    "precipProbability": 0.56,
                    "precipType": "rain",
                    "temperature": 18.39,
                    "apparentTemperature": 18.39,
                    "dewPoint": 17.62,
                    "humidity": 0.95,
                    "windSpeed": 21.98,
                    "windBearing": 31,
                    "cloudCover": 0.91,
                    "pressure": 1009.95,
                    "ozone": 316.94
                  },
                  {
                    "time": 1464822000,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.4343,
                    "precipProbability": 0.53,
                    "precipType": "rain",
                    "temperature": 17.79,
                    "apparentTemperature": 17.79,
                    "dewPoint": 17.22,
                    "humidity": 0.96,
                    "windSpeed": 21.1,
                    "windBearing": 35,
                    "cloudCover": 0.89,
                    "pressure": 1009.92,
                    "ozone": 317.27
                  },
                  {
                    "time": 1464825600,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.3429,
                    "precipProbability": 0.51,
                    "precipType": "rain",
                    "temperature": 17.41,
                    "apparentTemperature": 17.41,
                    "dewPoint": 16.96,
                    "humidity": 0.97,
                    "windSpeed": 19.63,
                    "windBearing": 40,
                    "cloudCover": 0.89,
                    "pressure": 1009.87,
                    "ozone": 317.64
                  },
                  {
                    "time": 1464829200,
                    "summary": "Drizzle",
                    "icon": "rain",
                    "precipIntensity": 0.2311,
                    "precipProbability": 0.46,
                    "precipType": "rain",
                    "temperature": 17.21,
                    "apparentTemperature": 17.21,
                    "dewPoint": 16.82,
                    "humidity": 0.98,
                    "windSpeed": 17.4,
                    "windBearing": 48,
                    "cloudCover": 0.92,
                    "pressure": 1009.78,
                    "ozone": 317.93
                  },
                  {
                    "time": 1464832800,
                    "summary": "Overcast",
                    "icon": "cloudy",
                    "precipIntensity": 0.1143,
                    "precipProbability": 0.18,
                    "precipType": "rain",
                    "temperature": 17.09,
                    "apparentTemperature": 17.09,
                    "dewPoint": 16.71,
                    "humidity": 0.98,
                    "windSpeed": 15.03,
                    "windBearing": 56,
                    "cloudCover": 0.97,
                    "pressure": 1009.68,
                    "ozone": 318.26
                  },
                  {
                    "time": 1464836400,
                    "summary": "Overcast",
                    "icon": "cloudy",
                    "precipIntensity": 0.033,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 17.04,
                    "apparentTemperature": 17.04,
                    "dewPoint": 16.58,
                    "humidity": 0.97,
                    "windSpeed": 13.07,
                    "windBearing": 62,
                    "cloudCover": 0.96,
                    "pressure": 1009.67,
                    "ozone": 318.41
                  },
                  {
                    "time": 1464840000,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 17.11,
                    "apparentTemperature": 17.11,
                    "dewPoint": 16.53,
                    "humidity": 0.96,
                    "windSpeed": 12.04,
                    "windBearing": 68,
                    "cloudCover": 0.87,
                    "pressure": 1009.82,
                    "ozone": 318.14
                  },
                  {
                    "time": 1464843600,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0203,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 17.26,
                    "apparentTemperature": 17.26,
                    "dewPoint": 16.5,
                    "humidity": 0.95,
                    "windSpeed": 11.62,
                    "windBearing": 73,
                    "cloudCover": 0.72,
                    "pressure": 1010.06,
                    "ozone": 317.69
                  },
                  {
                    "time": 1464847200,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0305,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 17.62,
                    "apparentTemperature": 17.62,
                    "dewPoint": 16.42,
                    "humidity": 0.93,
                    "windSpeed": 11.54,
                    "windBearing": 76,
                    "cloudCover": 0.56,
                    "pressure": 1010.23,
                    "ozone": 317.49
                  },
                  {
                    "time": 1464850800,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0229,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 18.47,
                    "apparentTemperature": 18.47,
                    "dewPoint": 16.36,
                    "humidity": 0.88,
                    "windSpeed": 11.94,
                    "windBearing": 77,
                    "cloudCover": 0.38,
                    "pressure": 1010.3,
                    "ozone": 317.64
                  },
                  {
                    "time": 1464854400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 19.83,
                    "apparentTemperature": 19.83,
                    "dewPoint": 16.44,
                    "humidity": 0.81,
                    "windSpeed": 12.36,
                    "windBearing": 74,
                    "cloudCover": 0.19,
                    "pressure": 1010.34,
                    "ozone": 318.03
                  },
                  {
                    "time": 1464858000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0279,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 21.32,
                    "apparentTemperature": 21.32,
                    "dewPoint": 16.78,
                    "humidity": 0.75,
                    "windSpeed": 12.65,
                    "windBearing": 69,
                    "cloudCover": 0.06,
                    "pressure": 1010.32,
                    "ozone": 318.87
                  },
                  {
                    "time": 1464861600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 22.69,
                    "apparentTemperature": 22.69,
                    "dewPoint": 17.41,
                    "humidity": 0.72,
                    "windSpeed": 12.2,
                    "windBearing": 64,
                    "cloudCover": 0.02,
                    "pressure": 1010.2,
                    "ozone": 320.53
                  },
                  {
                    "time": 1464865200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 23.81,
                    "apparentTemperature": 23.81,
                    "dewPoint": 18.06,
                    "humidity": 0.7,
                    "windSpeed": 11.54,
                    "windBearing": 55,
                    "cloudCover": 0.04,
                    "pressure": 1010.02,
                    "ozone": 322.62
                  },
                  {
                    "time": 1464868800,
                    "summary": "Drizzle",
                    "icon": "rain",
                    "precipIntensity": 0.193,
                    "precipProbability": 0.36,
                    "precipType": "rain",
                    "temperature": 24.39,
                    "apparentTemperature": 24.39,
                    "dewPoint": 18.48,
                    "humidity": 0.7,
                    "windSpeed": 11.01,
                    "windBearing": 47,
                    "cloudCover": 0.09,
                    "pressure": 1009.85,
                    "ozone": 324.23
                  },
                  {
                    "time": 1464872400,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.889,
                    "precipProbability": 0.61,
                    "precipType": "rain",
                    "temperature": 24.13,
                    "apparentTemperature": 24.13,
                    "dewPoint": 18.39,
                    "humidity": 0.7,
                    "windSpeed": 10.83,
                    "windBearing": 43,
                    "cloudCover": 0.18,
                    "pressure": 1009.69,
                    "ozone": 324.54
                  },
                  {
                    "time": 1464876000,
                    "summary": "Rain",
                    "icon": "rain",
                    "precipIntensity": 1.7805,
                    "precipProbability": 0.68,
                    "precipType": "rain",
                    "temperature": 23.38,
                    "apparentTemperature": 23.38,
                    "dewPoint": 18.09,
                    "humidity": 0.72,
                    "windSpeed": 10.64,
                    "windBearing": 42,
                    "cloudCover": 0.31,
                    "pressure": 1009.53,
                    "ozone": 324.35
                  },
                  {
                    "time": 1464879600,
                    "summary": "Rain",
                    "icon": "rain",
                    "precipIntensity": 2.2301,
                    "precipProbability": 0.7,
                    "precipType": "rain",
                    "temperature": 22.82,
                    "apparentTemperature": 22.82,
                    "dewPoint": 18.08,
                    "humidity": 0.75,
                    "windSpeed": 10.43,
                    "windBearing": 44,
                    "cloudCover": 0.42,
                    "pressure": 1009.42,
                    "ozone": 325.13
                  },
                  {
                    "time": 1464883200,
                    "summary": "Rain",
                    "icon": "rain",
                    "precipIntensity": 1.8085,
                    "precipProbability": 0.68,
                    "precipType": "rain",
                    "temperature": 22.68,
                    "apparentTemperature": 22.68,
                    "dewPoint": 18.64,
                    "humidity": 0.78,
                    "windSpeed": 10.11,
                    "windBearing": 50,
                    "cloudCover": 0.49,
                    "pressure": 1009.36,
                    "ozone": 327.85
                  },
                  {
                    "time": 1464886800,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.9296,
                    "precipProbability": 0.62,
                    "precipType": "rain",
                    "temperature": 22.88,
                    "apparentTemperature": 22.88,
                    "dewPoint": 19.59,
                    "humidity": 0.82,
                    "windSpeed": 9.41,
                    "windBearing": 57,
                    "cloudCover": 0.55,
                    "pressure": 1009.36,
                    "ozone": 331.53
                  },
                  {
                    "time": 1464890400,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.2946,
                    "precipProbability": 0.49,
                    "precipType": "rain",
                    "temperature": 22.52,
                    "apparentTemperature": 22.52,
                    "dewPoint": 19.87,
                    "humidity": 0.85,
                    "windSpeed": 9.99,
                    "windBearing": 64,
                    "cloudCover": 0.58,
                    "pressure": 1009.44,
                    "ozone": 334.75
                  },
                  {
                    "time": 1464894000,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.2718,
                    "precipProbability": 0.48,
                    "precipType": "rain",
                    "temperature": 21.48,
                    "apparentTemperature": 21.48,
                    "dewPoint": 19.31,
                    "humidity": 0.87,
                    "windSpeed": 10.91,
                    "windBearing": 65,
                    "cloudCover": 0.62,
                    "pressure": 1009.64,
                    "ozone": 337.35
                  },
                  {
                    "time": 1464897600,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.5258,
                    "precipProbability": 0.56,
                    "precipType": "rain",
                    "temperature": 20.21,
                    "apparentTemperature": 20.21,
                    "dewPoint": 18.43,
                    "humidity": 0.9,
                    "windSpeed": 11.57,
                    "windBearing": 63,
                    "cloudCover": 0.64,
                    "pressure": 1009.91,
                    "ozone": 339.48
                  },
                  {
                    "time": 1464901200,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.6807,
                    "precipProbability": 0.58,
                    "precipType": "rain",
                    "temperature": 19.05,
                    "apparentTemperature": 19.05,
                    "dewPoint": 17.58,
                    "humidity": 0.91,
                    "windSpeed": 11.75,
                    "windBearing": 60,
                    "cloudCover": 0.59,
                    "pressure": 1010.12,
                    "ozone": 340.23
                  },
                  {
                    "time": 1464904800,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.5207,
                    "precipProbability": 0.55,
                    "precipType": "rain",
                    "temperature": 18.16,
                    "apparentTemperature": 18.16,
                    "dewPoint": 16.88,
                    "humidity": 0.92,
                    "windSpeed": 11.12,
                    "windBearing": 63,
                    "cloudCover": 0.39,
                    "pressure": 1010.22,
                    "ozone": 338.72
                  },
                  {
                    "time": 1464908400,
                    "summary": "Light Rain",
                    "icon": "rain",
                    "precipIntensity": 0.3404,
                    "precipProbability": 0.51,
                    "precipType": "rain",
                    "temperature": 17.4,
                    "apparentTemperature": 17.4,
                    "dewPoint": 16.23,
                    "humidity": 0.93,
                    "windSpeed": 10.49,
                    "windBearing": 66,
                    "cloudCover": 0.21,
                    "pressure": 1010.24,
                    "ozone": 335.82
                  },
                  {
                    "time": 1464912000,
                    "summary": "Drizzle",
                    "icon": "rain",
                    "precipIntensity": 0.1626,
                    "precipProbability": 0.29,
                    "precipType": "rain",
                    "temperature": 16.74,
                    "apparentTemperature": 16.74,
                    "dewPoint": 15.64,
                    "humidity": 0.93,
                    "windSpeed": 9.96,
                    "windBearing": 68,
                    "cloudCover": 0.03,
                    "pressure": 1010.24,
                    "ozone": 333.24
                  },
                  {
                    "time": 1464915600,
                    "summary": "Drizzle",
                    "icon": "rain",
                    "precipIntensity": 0.1448,
                    "precipProbability": 0.25,
                    "precipType": "rain",
                    "temperature": 16.22,
                    "apparentTemperature": 16.22,
                    "dewPoint": 15.21,
                    "humidity": 0.94,
                    "windSpeed": 9.41,
                    "windBearing": 70,
                    "cloudCover": 0.02,
                    "pressure": 1010.21,
                    "ozone": 331.63
                  },
                  {
                    "time": 1464919200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0914,
                    "precipProbability": 0.13,
                    "precipType": "rain",
                    "temperature": 15.57,
                    "apparentTemperature": 15.57,
                    "dewPoint": 14.63,
                    "humidity": 0.94,
                    "windSpeed": 8.95,
                    "windBearing": 73,
                    "cloudCover": 0.02,
                    "pressure": 1010.14,
                    "ozone": 330.34
                  },
                  {
                    "time": 1464922800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0305,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 15.29,
                    "apparentTemperature": 15.29,
                    "dewPoint": 14.32,
                    "humidity": 0.94,
                    "windSpeed": 8.72,
                    "windBearing": 74,
                    "cloudCover": 0.01,
                    "pressure": 1010.12,
                    "ozone": 329.02
                  },
                  {
                    "time": 1464926400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 15.43,
                    "apparentTemperature": 15.43,
                    "dewPoint": 14.31,
                    "humidity": 0.93,
                    "windSpeed": 8.92,
                    "windBearing": 70,
                    "cloudCover": 0.02,
                    "pressure": 1010.19,
                    "ozone": 327.65
                  },
                  {
                    "time": 1464930000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 14.88,
                    "apparentTemperature": 14.88,
                    "dewPoint": 13.51,
                    "humidity": 0.91,
                    "windSpeed": 9.46,
                    "windBearing": 62,
                    "cloudCover": 0.04,
                    "pressure": 1010.3,
                    "ozone": 326.27
                  },
                  {
                    "time": 1464933600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 15.92,
                    "apparentTemperature": 15.92,
                    "dewPoint": 14.11,
                    "humidity": 0.89,
                    "windSpeed": 10.09,
                    "windBearing": 57,
                    "cloudCover": 0.08,
                    "pressure": 1010.41,
                    "ozone": 324.59
                  },
                  {
                    "time": 1464937200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0356,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 17.12,
                    "apparentTemperature": 17.12,
                    "dewPoint": 14.56,
                    "humidity": 0.85,
                    "windSpeed": 10.04,
                    "windBearing": 59,
                    "cloudCover": 0.17,
                    "pressure": 1010.5,
                    "ozone": 322.15
                  },
                  {
                    "time": 1464940800,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0686,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 18.64,
                    "apparentTemperature": 18.64,
                    "dewPoint": 15.07,
                    "humidity": 0.8,
                    "windSpeed": 9.77,
                    "windBearing": 64,
                    "cloudCover": 0.29,
                    "pressure": 1010.59,
                    "ozone": 319.43
                  },
                  {
                    "time": 1464944400,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0991,
                    "precipProbability": 0.15,
                    "precipType": "rain",
                    "temperature": 20.26,
                    "apparentTemperature": 20.26,
                    "dewPoint": 15.61,
                    "humidity": 0.75,
                    "windSpeed": 9.83,
                    "windBearing": 68,
                    "cloudCover": 0.39,
                    "pressure": 1010.63,
                    "ozone": 317.52
                  },
                  {
                    "time": 1464948000,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.1143,
                    "precipProbability": 0.18,
                    "precipType": "rain",
                    "temperature": 21.87,
                    "apparentTemperature": 21.87,
                    "dewPoint": 16.09,
                    "humidity": 0.7,
                    "windSpeed": 10.48,
                    "windBearing": 71,
                    "cloudCover": 0.45,
                    "pressure": 1010.57,
                    "ozone": 317.12
                  },
                  {
                    "time": 1464951600,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.1219,
                    "precipProbability": 0.2,
                    "precipType": "rain",
                    "temperature": 23.34,
                    "apparentTemperature": 23.34,
                    "dewPoint": 16.47,
                    "humidity": 0.65,
                    "windSpeed": 11.36,
                    "windBearing": 73,
                    "cloudCover": 0.49,
                    "pressure": 1010.47,
                    "ozone": 317.53
                  },
                    {
                        "time": 1464955200,
                        "summary": "Drizzle",
                        "icon": "rain",
                        "precipIntensity": 0.1448,
                        "precipProbability": 0.25,
                        "precipType": "rain",
                        "temperature": 24.34,
                        "apparentTemperature": 24.34,
                        "dewPoint": 16.82,
                        "humidity": 0.63,
                        "windSpeed": 12.09,
                        "windBearing": 73,
                        "cloudCover": 0.51,
                        "pressure": 1010.37,
                        "ozone": 317.86
                    }
                ]
            },
            "daily": {
                "summary": "Light rain throughout the week, with temperatures peaking at 26°C on Tuesday.",
                "icon": "rain",
                "data": [
                    {
                        "time": 1464732000,
                        "summary": "Light rain in the morning and afternoon.",
                        "icon": "rain",
                        "sunriseTime": 1464750987,
                        "sunsetTime": 1464810038,
                        "moonPhase": 0.86,
                        "precipIntensity": 0.4496,
                        "precipIntensityMax": 1.2116,
                        "precipIntensityMaxTime": 1464804000,
                        "precipProbability": 0.64,
                        "precipType": "rain",
                        "temperatureMin": 14.81,
                        "temperatureMinTime": 1464742800,
                        "temperatureMax": 24.32,
                        "temperatureMaxTime": 1464793200,
                        "apparentTemperatureMin": 14.81,
                        "apparentTemperatureMinTime": 1464742800,
                        "apparentTemperatureMax": 24.32,
                        "apparentTemperatureMaxTime": 1464793200,
                        "dewPoint": 17.74,
                        "humidity": 0.91,
                        "windSpeed": 12.68,
                        "windBearing": 12,
                        "cloudCover": 0.64,
                        "pressure": 1012,
                        "ozone": 319.25
                    },
                    {
                        "time": 1464818400,
                        "summary": "Rain starting in the afternoon.",
                        "icon": "rain",
                        "sunriseTime": 1464837340,
                        "sunsetTime": 1464896503,
                        "moonPhase": 0.9,
                        "precipIntensity": 0.475,
                        "precipIntensityMax": 2.2301,
                        "precipIntensityMaxTime": 1464879600,
                        "precipProbability": 0.7,
                        "precipType": "rain",
                        "temperatureMin": 17.04,
                        "temperatureMinTime": 1464836400,
                        "temperatureMax": 24.39,
                        "temperatureMaxTime": 1464868800,
                        "apparentTemperatureMin": 17.04,
                        "apparentTemperatureMinTime": 1464836400,
                        "apparentTemperatureMax": 24.39,
                        "apparentTemperatureMaxTime": 1464868800,
                        "dewPoint": 17.62,
                        "humidity": 0.85,
                        "windSpeed": 12.57,
                        "windBearing": 55,
                        "cloudCover": 0.54,
                        "pressure": 1009.85,
                        "ozone": 323.62
                    },
                    {
                        "time": 1464904800,
                        "summary": "Light rain starting in the afternoon.",
                        "icon": "rain",
                        "sunriseTime": 1464923697,
                        "sunsetTime": 1464982966,
                        "moonPhase": 0.94,
                        "precipIntensity": 0.1803,
                        "precipIntensityMax": 0.5207,
                        "precipIntensityMaxTime": 1464904800,
                        "precipProbability": 0.55,
                        "precipType": "rain",
                        "temperatureMin": 14.88,
                        "temperatureMinTime": 1464930000,
                        "temperatureMax": 24.68,
                        "temperatureMaxTime": 1464958800,
                        "apparentTemperatureMin": 14.88,
                        "apparentTemperatureMinTime": 1464930000,
                        "apparentTemperatureMax": 24.68,
                        "apparentTemperatureMaxTime": 1464958800,
                        "dewPoint": 15.95,
                        "humidity": 0.82,
                        "windSpeed": 10.46,
                        "windBearing": 68,
                        "cloudCover": 0.27,
                        "pressure": 1010.35,
                        "ozone": 323.33
                    },
                    {
                        "time": 1464991200,
                        "summary": "Light rain throughout the day.",
                        "icon": "rain",
                        "sunriseTime": 1465010056,
                        "sunsetTime": 1465069427,
                        "moonPhase": 0.97,
                        "precipIntensity": 0.2108,
                        "precipIntensityMax": 0.508,
                        "precipIntensityMaxTime": 1465034400,
                        "precipProbability": 0.55,
                        "precipType": "rain",
                        "temperatureMin": 14.19,
                        "temperatureMinTime": 1465005600,
                        "temperatureMax": 24.87,
                        "temperatureMaxTime": 1465048800,
                        "apparentTemperatureMin": 14.19,
                        "apparentTemperatureMinTime": 1465005600,
                        "apparentTemperatureMax": 24.87,
                        "apparentTemperatureMaxTime": 1465048800,
                        "dewPoint": 15.63,
                        "humidity": 0.82,
                        "windSpeed": 11.01,
                        "windBearing": 44,
                        "cloudCover": 0.07,
                        "pressure": 1011.96,
                        "ozone": 332.8
                    },
                    {
                        "time": 1465077600,
                        "summary": "Light rain starting in the afternoon.",
                        "icon": "rain",
                        "sunriseTime": 1465096418,
                        "sunsetTime": 1465155885,
                        "moonPhase": 0.02,
                        "precipIntensity": 0.3124,
                        "precipIntensityMax": 1.2675,
                        "precipIntensityMaxTime": 1465138800,
                        "precipProbability": 0.65,
                        "precipType": "rain",
                        "temperatureMin": 14.62,
                        "temperatureMinTime": 1465092000,
                        "temperatureMax": 25.04,
                        "temperatureMaxTime": 1465135200,
                        "apparentTemperatureMin": 14.62,
                        "apparentTemperatureMinTime": 1465092000,
                        "apparentTemperatureMax": 25.04,
                        "apparentTemperatureMaxTime": 1465135200,
                        "dewPoint": 15.9,
                        "humidity": 0.83,
                        "windSpeed": 12.34,
                        "windBearing": 48,
                        "cloudCover": 0.2,
                        "pressure": 1015.53,
                        "ozone": 335.05
                    },
                    {
                        "time": 1465164000,
                        "summary": "Partly cloudy overnight.",
                        "icon": "partly-cloudy-night",
                        "sunriseTime": 1465182783,
                        "sunsetTime": 1465242341,
                        "moonPhase": 0.05,
                        "precipIntensity": 0.0178,
                        "precipIntensityMax": 0.033,
                        "precipIntensityMaxTime": 1465171200,
                        "precipProbability": 0.02,
                        "precipType": "rain",
                        "temperatureMin": 13.24,
                        "temperatureMinTime": 1465178400,
                        "temperatureMax": 25.77,
                        "temperatureMaxTime": 1465221600,
                        "apparentTemperatureMin": 13.24,
                        "apparentTemperatureMinTime": 1465178400,
                        "apparentTemperatureMax": 25.77,
                        "apparentTemperatureMaxTime": 1465221600,
                        "dewPoint": 13.88,
                        "humidity": 0.75,
                        "windSpeed": 12.44,
                        "windBearing": 83,
                        "cloudCover": 0.06,
                        "pressure": 1018.76,
                        "ozone": 336.25
                    },
                    {
                        "time": 1465250400,
                        "summary": "Light rain starting in the afternoon.",
                        "icon": "rain",
                        "sunriseTime": 1465269151,
                        "sunsetTime": 1465328794,
                        "moonPhase": 0.09,
                        "precipIntensity": 0.1753,
                        "precipIntensityMax": 0.7112,
                        "precipIntensityMaxTime": 1465329600,
                        "precipProbability": 0.59,
                        "precipType": "rain",
                        "temperatureMin": 12.08,
                        "temperatureMinTime": 1465268400,
                        "temperatureMax": 25.97,
                        "temperatureMaxTime": 1465304400,
                        "apparentTemperatureMin": 12.08,
                        "apparentTemperatureMinTime": 1465268400,
                        "apparentTemperatureMax": 25.97,
                        "apparentTemperatureMaxTime": 1465304400,
                        "dewPoint": 13.62,
                        "humidity": 0.73,
                        "windSpeed": 6.28,
                        "windBearing": 78,
                        "cloudCover": 0.5,
                        "pressure": 1017.99,
                        "ozone": 334.77
                    },
                    {
                        "time": 1465336800,
                        "summary": "Mostly cloudy until evening.",
                        "icon": "partly-cloudy-day",
                        "sunriseTime": 1465355522,
                        "sunsetTime": 1465415245,
                        "moonPhase": 0.12,
                        "precipIntensity": 0.0991,
                        "precipIntensityMax": 0.602,
                        "precipIntensityMaxTime": 1465336800,
                        "precipProbability": 0.57,
                        "precipType": "rain",
                        "temperatureMin": 10.87,
                        "temperatureMinTime": 1465354800,
                        "temperatureMax": 22.31,
                        "temperatureMaxTime": 1465394400,
                        "apparentTemperatureMin": 10.87,
                        "apparentTemperatureMinTime": 1465354800,
                        "apparentTemperatureMax": 22.31,
                        "apparentTemperatureMaxTime": 1465394400,
                        "dewPoint": 12.42,
                        "humidity": 0.77,
                        "windSpeed": 10.83,
                        "windBearing": 7,
                        "cloudCover": 0.85,
                        "pressure": 1018.8,
                        "ozone": 336.64
                    }
                ]
          },
          "flags": {
                "sources": [
                      "gfs",
                      "cmc",
                      "fnmoc",
                      "metno_ne",
                      "metno_ce",
                      "isd",
                      "madis"
                ],
                "metno-license": "Based on data from the Norwegian Meteorological Institute. (http://api.met.no/)",
                "isd-stations": [
                    "103070-99999",
                    "103130-99999",
                    "103134-99999",
                    "103150-99999",
                    "103170-99999"
                ],
                "madis-stations": [
                    "EDDG",
                    "EDLW",
                    "ETHE"
                ],
                "units": "ca"
            }
        }